### ISSUE TITLE
Measurements off by 15px

### ISSUE THREAD

**Issue by RenaissanceBug** [mirkosantangelo/Responsive-Browser#1]
It appears that on my computer (Yosemite 10.10.3, Safari 8.0.6), widths in this extension are smaller than actual, typically by about 15px. Using these media queries:

``` css
@media only screen and (max-width: 400px) { #small { background-color: green; } }
@media only screen and (min-width: 401px) and (max-width: 800px) {
    #medium { background-color: green; }
} 
@media only screen and (min-width: 801px) { #large { background-color: green; } }
```

...on this HTML:

``` html
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test media query width values</title>
    <link rel="stylesheet" type="text/css" href="mq-common.css">
    <link rel="stylesheet" type="text/css" href="mq-widths-nonoverlapping.css">
</head>
<body>
    <div class="main">
        <div id="small">Small query active</div>
        <div id="medium">Medium query active</div>
        <div id="large">Large query active</div>
    </div>
</body>
</html>
```

...together with some CSS to style the small/med/large DIVs in red by default, I find the media query boundaries occur not at 400-401 and 800-801 but at 385-386 and 785-786 as reported by the extension. 
An example screenshot:
![screen shot 2015-06-20 at 9 26 10 pm](https://cloud.githubusercontent.com/assets/3138906/8270390/0e0c190e-1793-11e5-9cbf-9b330d555a51.png)
(I'll send the full HTML/CSS if you want.)

I double-checked that the media queries themselves are OK, by using window.resizeTo(); the queries kick in at the right numbers when the window size is set that way, so it appears that the extension's not using the same width measurement the browser uses.

I'm using a 4K display, in case that's related to the method of measuring.
